# Generated by Django 4.2.15 on 2024-09-18 15:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0009_alter_event_options_remove_event_date_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dsojbqe7b/image/upload/v1726670855/bmecfws82yver9zuiq8u.jpg', max_length=255, verbose_name='image'),
        ),
    ]
