# Generated by Django 4.2.15 on 2024-10-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0011_userprofile_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
    ]
